"""change course id to g

Revision ID: c8b185b87f44
Revises: 
Create Date: 2025-12-13 17:38:47.652492

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c8b185b87f44'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('user',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=True),
    sa.Column('email', sa.String(length=150), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('course',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('courseName', sa.String(length=50), nullable=False),
    sa.Column('subjectName', sa.String(length=50), nullable=False),
    sa.Column('owner_id', sa.String(length=200), nullable=False),
    sa.ForeignKeyConstraint(['owner_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('course_members',
    sa.Column('user_id', sa.String(length=200), nullable=False),
    sa.Column('course_id', sa.String(length=20), nullable=False),
    sa.ForeignKeyConstraint(['course_id'], ['course.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('user_id', 'course_id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('course_members')
    op.drop_table('course')
    op.drop_table('user')
    # ### end Alembic commands ###
